services:
  postgres:
    env_file: local.env
    container_name: '${DB_NAME}'
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${DB_NAME}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_USER=${DB_USERNAME}'
    ports:
      - '${DB_PORT}:5432'
