spring:
  application:
    name: Kokoro-API
  datasource:
    username: ${DB_USERNAME}
    name: ${DB_NAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /docs/swagger
jwt:
  secret: ${JWT_SECRET}
  expiration: 604800000 # 7 days
  issuer: kokoro